### ISSUE TITLE
Crashes when opening control menu in combination with Optifine/optiforge/mixingbootstrap

### ISSUE THREAD

**Issue by roninvanderwerke** [LXGaming/MixinBootstrap#11]
Client crashes when opening control menu in combination with Optifine/optiforge/mixingbootstrap

Forge 31.1.30
Optifine 1.15.2 pre 13 MOD
Optiforge MC1.15.2-0.2.17
Mixing Bootsrap-1.0.2

Controlling 5.0.6

**Comment by LXGaming** [comment]
[crash-2020-04-07_11.43.34-client.txt](https://github.com/LXGaming/MixinBootstrap/files/4441307/crash-2020-04-07_11.43.34-client.txt)

I reproduced the issue and got the crash report above. This is an issue with [jaredlll08/Controlling](https://github.com/jaredlll08/Controlling), the mod needs to updated in order to be compatible with the latest Forge versions.

The cause of the crash is due to a NoSuchFieldError which is caused by this line [ClientEventHandler.java#L16](https://github.com/jaredlll08/Controlling/blob/26babf52d2fa97d524dac9712a16816dfdc4bb03/src/main/java/com/blamejared/controlling/events/ClientEventHandler.java#L16)
