### ISSUE TITLE
[1.15.2] Crash on startup

### ISSUE THREAD

**Issue by LeoNoawi** [LXGaming/MixinBootstrap#12]
Hello,
When MixinBootstrap is enabled the game crashes when launched, game starts completely normally when it's disabled.
I'm also trying to use it with Optiforge 0.1.8 and preview Optifine 1.15.2 G1 pre13 but neither were enabled when launched. And i use MultiMC to launch instances if that might be an issue.

Forge: 31.1.44 (also tried with 31.1.39)

[crash-2020-04-13_16.22.47-client.txt](https://github.com/LXGaming/MixinBootstrap/files/4469958/crash-2020-04-13_16.22.47-client.txt)

**Comment by LXGaming** [comment]
Please provide your debug.log file as that will help track down root cause of this issue.

**Comment by LeoNoawi** [comment]
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4470052/debug.log)

**Comment by LXGaming** [comment]
Looks like the issue is due to lithium, They are attempting to change the visibility of a method which is not allowed, This is then preventing the Entity class from being loaded which is breaking other mods.

The crash report is a bit miss leading as the error is due to the Forge EventBus shutting down due to the several mods throwing errors regarding a missing Entity class.

Try setting `use_optimized_data_tracker` to `false` in the lithium config.

**Comment by LeoNoawi** [comment]
Worked perfectly, thank you so much!
