### ISSUE TITLE
Game crashes without opening

### ISSUE THREAD

**Issue by vizthex123** [LXGaming/MixinBootstrap#38]
**Environment**
- MixinBootstrap version: 1.0.5
- Forge version: 14.23.5.2854
- Minecraft version: 1.12.2
- Java version:  Java 8 update 261
- Mods: A lot. [It happens in my new modpack.](https://www.curseforge.com/minecraft/modpacks/capitalia)

**Issue Description**
The game crashes without even opening. Adding [Mixin Compat](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) fixes this issue.

Here's the log: [https://pastebin.com/vC2fipVV](https://pastebin.com/vC2fipVV)

**Comment by LXGaming** [comment]
Looks like the issue is caused by Durability101 loading in Mixin v0.7.11 but VanillaFix requires Mixin v0.8+.
MixinCompact fixes this by having a file name which gets loaded by Forge first which then causes Mixin v0.8 to get loaded instead.

You can ether rename MixinBootstrap to be loaded first or simply remove it and just use MixinCompact.

**Comment by vizthex123** [comment]
Yeah I use Mixin Compat, but it'd be nice to have this fixed in Mixin Bootstrap; if possible.

**Comment by LXGaming** [comment]
Sadly it's not something that can be fixed, The solution is to rename the file.
