### ISSUE TITLE
Crash but I don't know which mod causes it.

### ISSUE THREAD

**Issue by Kasia1403** [LXGaming/MixinBootstrap#50]
[crash-2021-11-28_21.06.08-client.txt](https://github.com/LXGaming/MixinBootstrap/files/7614298/crash-2021-11-28_21.06.08-client.txt)

**Comment by LXGaming** [comment]
Can you please provided your debug.log file.

**Comment by Kasia1403** [comment]
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/7616837/debug.log)

Is it this file ?

**Comment by LXGaming** [comment]
Hmm, It's crashing due to `java.lang.ClassNotFoundException: paulscode.sound.libraries.LibraryLWJGLOpenAL` however I can't see anything in the logs that would point to this being a Mixin issue.

My only guess is that a library is corrupt, I recommend deleting the `E:\Pobrane\MultiMC\MultiMC\libraries\com\paulscode\` folder, MultiMC should automatically re-download the libraries.

**Comment by Kasia1403** [comment]
Will it help if it's hacked launcher ( hacked by Hackphoenix ) ?

**Comment by Kasia1403** [comment]
I deleted this folder and still the same. :( Maybe one of mods is messing with this library ?

**Comment by Kasia1403** [comment]
How to send You entire MultiMC folder ?

**Comment by LXGaming** [comment]
Launcher won't be helping.

Best thing to do would be to check if Vanilla 1.12.2 launches without issues, Then check if Forge 1.12.2 with no mods launches without issues as that will then point to mods being the issue
