### ISSUE TITLE
This mod + Phosphor = Crash. (This seems to be a different crash from #52, so please don't just instaclose this.)

### ISSUE THREAD

**Issue by MagmaSlime123** [LXGaming/MixinBootstrap#54]
**Environment**
- MixinBootstrap version: 1.1.0.
- Forge version: 2860.
- Minecraft version: 1.12.2.
- Java version: Don't know how to find this.
- Mods: See the crash report.

**Issue Description**
Title. This mod when used with Phosphor will crash. This seems to be a different crash from #52, so please don't just instaclose this.

https://pastebin.com/W3wiPrGi

**Comment by LXGaming** [comment]
> This seems to be a different crash from https://github.com/LXGaming/MixinBootstrap/issues/52

Comparing the logs provided in both issues they are crashing at different points but they have the exact same root cause which is:
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method setBlockStateInjectGenerateSkylightMapVanilla(Z)Z in mixins.phosphor.json:common.MixinChunk$Vanilla failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.phosphor.refmap.json
```

The solution for this issue is in #52 which is to ether remove MixinBootstrap or according to mxnmnm use `mixin 0.7-0.8 compat` instead.

Please note: **There is nothing I can do about this, MixinBootstrap simply adds the Mixin library to Minecraft I can't change Mixin to make it compatible with mods.**
